#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/utils/jobscript

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J atlas_top_delphes_test
#SBATCH --mail-user=mingfong@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH -A m3246
#SBATCH -t 24:00:00

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

date
set -x    # log commands
image=vmikuni/tensorflow:ngc-23.12-tf2-v1

#run the application: 

srun -l -u --mpi=pmi2 shifter --image=$image \
  bash -c "python preprocessing/preprocess_atlas.py --folder /pscratch/sd/m/mingfong/omnilearn/ --sample delphes_test.h5"

date
